name: basic-local-llama3-env  # Replace with your desired environment name
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.12  # Optional: specify a Python version
  - pip
  - annotated-types
  - certifi
  - charset-normalizer
  - idna
  - jinja2
  - markupsafe
  - pillow
  - pydantic
  - pydantic-core
  - pyyaml
  - regex
  - requests
  - tiktoken
  - typing-extensions
  - urllib3
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - flask
  - fire
  - flask-cors
  
  - pip:
    
    